[W5.11][W13-3]ChelseyOng
nusCS2113-AY1819S1/addressbook-level2 pull request #23
Opened 2018-09-08 09:17 UTC by chelseyong

Added an 'Edit' command. Updated the user guide, test cases and unit tests.

2018-09-11 09:08 UTC, emobeany commented
I am still picking up Java so there are still a lot of gaps in my knowledge. But good job following the coding standards! :) 

One suggestion (I have no idea how to) could be to allow users to edit only one detail rather than having to edit or type all the details again when calling the edit command. 

Good job nonetheless!

2018-09-11 10:37 UTC, emobeany requested changes
I am still picking up Java so there are still a lot of gaps in my knowledge. But good job following the coding standards! :)

One suggestion (I have no idea how to) could be to allow users to edit only one detail rather than having to edit or type all the details again when calling the edit command.

Good job nonetheless!

2018-09-15 08:55 UTC, Sri-vatsa approved these changes
👍 👍It is great to see that you have implemented a more challenging feature. Great work on writing JUnit tests, updating docs as well. 

Perhaps, you could think about how you can work with only editing only some fields, instead of editing all details each time. 

Please look through my comments and close the PR

2018-09-15 08:55 UTC, Sri-vatsa commented on src/seedu/addressbook/commands/HelpCommand.java
> +                + "\n" + EditCommand.MESSAGE_USAGE
👍

2018-09-15 08:55 UTC, Sri-vatsa commented on src/seedu/addressbook/parser/Parser.java
> +import seedu.addressbook.commands.*;
It is always a good practice to only import the classes needed and not import all.

2018-09-15 08:55 UTC, Sri-vatsa commented on src/seedu/addressbook/parser/Parser.java
> +     * Parses arguments in the context of the edit person command.
Commenting code is a good practice!

2018-09-15 08:55 UTC, Sri-vatsa commented on test/expected.txt
>  ||
Great to see that you have added tests as well :)

2018-09-15 08:55 UTC, Sri-vatsa commented on test/java/seedu/addressbook/commands/EditCommandTest.java
> +}
Good attempt 👍

2018-09-15 08:55 UTC, Sri-vatsa commented on src/seedu/addressbook/parser/Parser.java
>  import seedu.addressbook.data.exception.IllegalValueException;
Great that you have noticed this coding violation and fixed it :)

2018-09-15 08:55 UTC, Sri-vatsa commented on docs/UserGuide.adoc
> +
👍

2018-09-15 14:24 UTC, chel-seyy commented
Noted thanks!

2018-09-15 14:24 UTC, closed without merging