[W5.11][W12-1]Elston Aw
nusCS2113-AY1819S1/addressbook-level2 pull request #95
Opened 2018-09-11 11:33 UTC by elstonayx

Ready for review.

2018-09-11 11:35 UTC, bennchong commented
Made commands into non-case sensitive. Really helpful when commands are entered quickly. +1 for being a beast climber

2018-09-11 12:57 UTC, jitwei98 requested changes
Smart enhancement to have here.
Would like to see some test to know if it works or not.

2018-09-11 15:26 UTC, driedmelon commented on src/seedu/addressbook/parser/Parser.java
> +        final String commandWord = matcher.group("commandWord").toLowerCase();
good for convenience

2018-09-11 15:26 UTC, sylchw approved these changes
Good change for convenience

2018-09-16 02:08 UTC, okkhoy approved these changes
This enhancement surely gives you a tick mark on the graded LO.
However, not sure if the intended objective of being able to work with an intermediate size codebase was achieved.

2018-09-16 02:08 UTC, okkhoy commented
@elstonayx 
Some comments added. Please take note and close the pull request.

2018-09-16 14:49 UTC, closed without merging